name: Trigger Kata Tests

on:
  push:
    branches:
      - main
#    paths:
#      - 'katas/**'

jobs:
  get-katas-to-test:
    runs-on: ubuntu-latest
    outputs:
      changed_katas: ${{ steps.katas_to_test.outputs.katas }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find Katas to test
        id: katas_to_test
        run: |
          CHANGED_KATAS=$(git diff --name-only origin/main HEAD | grep '^katas/' | uniq)
          if [ -z "$CHANGED_KATAS" ]; then
            echo "No katas have changed."
            echo "::set-output name=katas::[]"
          else
            echo "Changed katas: $CHANGED_KATAS"
            KATAS_JSON=$(echo $CHANGED_KATAS | jq -R -s 'split("\n")')
            echo "::set-output name=katas::$KATAS_JSON"
          fi

  test-katas:
    needs: get-katas-to-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kata_name: ${{ fromJson(needs.get-katas-to-test.outputs.changed_katas) }}
    steps:
      - name: Trigger general kata test workflow
        uses: ./.github/workflows/test-kata.yaml
        with:
          kata_name: ${{ matrix.kata_name }}
