name: Python Katas Testing

jobs:
  PythonKatas:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/python_katas/')  }}
    steps:
      - uses: actions/checkout@v2
      - name: Test katas
        run: |
          pip install requests pytube
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          cd python_katas
          cp test/_score.py .
          python _score.py

  PythonKatasLinting:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ startsWith(github.ref, 'refs/heads/python_katas/')  }}
    steps:
      - uses: actions/checkout@v2
      - name: install pylint
        run: |
          pip install pylint
      - name: Linting test
        run: |
          cd python_katas
          pylint *.py || true
